#
# Docker Env for Testing and Benchmarking.
#
# ---------------------------------------------------------------------------------------------------------------------
services:
  pluto:
    image: pluto
    build:
      context: .
      dockerfile: docker/pluto/dockerfile
    ports:
      - "10000:8000"
    healthcheck:
      test: curl --fail http://localhost:8000/health/ || exit 1
      interval: 5s
      timeout: 5s
      retries: 10
      start_period: 5s
# ---------------------------------------------------------------------------------------------------------------------
