[build-system]
requires = ["setuptools >= 75"]
build-backend = "setuptools.build_meta"

[project]
name = "PlutoFilter"
version = "0.0.0"
authors = [
  { name="Philipp Kroll", email="pk@eample.com" },
]
description = "This Node filters incoming Events by their Event-Id. Evnets with matching Event-Ids will be passed along."
readme = "README.md"
requires-python = ">=3.8"
classifiers = [
    "Programming Language :: Python :: 3",
    "Operating System :: OS Independent",
]

[project.license]
file = "LICENSE"
license = "MIT"
license-files = ["LICENSE"]

[project.urls]
Homepage = "https://github.com/Philipp-Co/pluto"
Issues = "https://github.com/Philipp-Co/pluto/issues"
