#ifndef __PLUTO_OS_ABSTRACTION_CONFIG_H__
#define __PLUTO_OS_ABSTRACTION_CONFIG_H__

#if !defined(PLUTO_MESSAGE_QUEUE_CUSTOM_0) && !defined(PLUTO_MESSAGE_QUEUE_SYSTEM_V)
#define PLUTO_MESSAGE_QUEUE_SYSTEM_V 1
#endif

#endif
