# https://docs.docker.com/build/building/multi-stage/

#
# ---------------------------------------------------------------------------------------------------------------------
#
from ubuntu:20.04 as builder

RUN apt-get update && apt-get upgrade -y
RUN apt-get install cmake -y
RUN apt-get install python3-dev -y
RUN apt-get install git -y

COPY ../pluto_node/ /pluto_node/
COPY ../pluto_rw/ /pluto_rw/
COPY ../pluto_info/ /pluto_info/
COPY ../CMakeLists.txt /
RUN cd / && mkdir /external/ && cd /external/ && git clone https://github.com/zserge/jsmn.git  

RUN mkdir /build/ && cd /build/ && cmake -G "Unix Makefiles" ../ && make

#
# ---------------------------------------------------------------------------------------------------------------------
#
from ubuntu:20.04

RUN apt-get update
RUN apt-get install python3 -y

COPY --from=builder /build/pluto_node/pluto_node_pt /bin/pluto_node_pt 
COPY --from=builder /build/pluto_info/pluto_info /bin/pluto_info 
COPY --from=builder /build/pluto_rw/pluto_rw /bin/pluto_rw

RUN echo {\"work_dir\":\"/pluto/ipc/\",\"name_of_input_queue\":\"pluto-0_iq\",\"names_of_output_queues\":[\"pluto-0_oq_0\"]} > /pluto-0-config.txt

ENV PLUTO_PYTHON_PATH=/usr/lib/python38.zip;/usr/lib/python3.8;/usr/lib/python3.8/lib-dynload;/usr/local/lib/python3.8/dist-packages;/usr/lib/python3/dist-packages

CMD ["/pluto_node_pt", "-n", "pluto-0", "-c", "/pluto-0-config.txt"]
#
# ---------------------------------------------------------------------------------------------------------------------

