#
# ---------------------------------------------------------------------------------------------------------------------
#
# https://docs.docker.com/build/building/multi-stage/
from ubuntu:20.04

ARG BINARY_DIR /usr/local/bin/
ARG PLUTO_CORE pluto_core
ARG PLUTO_NODE pluto_node

#
# ---------------------------------------------------------------------------------------------------------------------
#
#RUN echo "Europe/Berlin" > /etc/timezone
#RUN export LD_LIBRARY_PATH=lib/aarch64-linux-gnu/:$LS_LIBRARY_PATH
RUN ln -snf /usr/share/zoneinfo/$CONTAINER_TIMEZONE /etc/localtime && echo $CONTAINER_TIMEZONE > /etc/timezone
RUN apt-get update
# RUN apt install software-properties-common -y
#
# ---------------------------------------------------------------------------------------------------------------------

# pluto-0 -- pluto_node_pt

COPY --from=pluto:latest $BINARY_DIR$PLUTO_NODE_pt $BINARY_DIR$PLUTO_NODE_pt
RUN echo {\"work_dir\":\"/pluto/ipc/\",\"name_of_input_queue\":\"pluto-0_iq\",\"names_of_output_queues\":[\"pluto-0_oq_0\"]} > /pluto-0-config.txt

#
# ---------------------------------------------------------------------------------------------------------------------
#

#pluto-1 -- pluto_node_py
#
# python3.8 and python3.8-dev must be available
#
#RUN add-apt-repository ppa:deadsnakes/ppa
RUN apt-get install python3.8-dev -y
COPY --from=pluto:latest $BINARY_DIR$PLUTO_NODE_py $BINARY_DIR$PLUTO_NODE_py
RUN echo {\"work_dir\":\"/pluto/ipc/\",\"python_path\":\"/pluto/\",\"name_of_input_queue\":\"pluto-0_oq_0\",\"names_of_output_queues\":[\"pluto-1_oq_0\"]} > /pluto-1-config.txt
COPY docker/demo/pluto_python_demo/pluto_event_handler.py /pluto/

#
# ---------------------------------------------------------------------------------------------------------------------
#

COPY --from=pluto:latest $BINARY_DIR$PLUTO_CORE $BINARY_DIR$PLUTO_CORE
ENV PLUTO_BINARY_DIR=/usr/local/bin/
RUN echo {\"nodes\":[\
    {\"type\":\"passthrough\",\"name\":\"pluto-0\",\"configuration-file\":\"/pluto-0-config.txt\",\"executable\":\"\"},\
    {\"type\":\"python\",\"name\":\"pluto-1\",\"configuration-file\":\"/pluto-1-config.txt\",\"executable\":\"pluto_event_handler\"}\
  ]\
} > /pluto-core.txt

#
# ---------------------------------------------------------------------------------------------------------------------
#
COPY --from=pluto:latest /plyto/dist/plyto-0.0.0.tar.gz /plyto-0.0.0.tar.gz
RUN python3 -m pip install /plyto-0.0.0.tar.gz
#
# ---------------------------------------------------------------------------------------------------------------------
#
#
# Entrypoint.
#
COPY docker/demo/entrypoint.sh /entrypoint.sh
RUN chmod +x /entrypoint.sh

#
# Finish...
#
CMD ["/entrypoint.sh"]
#
# ---------------------------------------------------------------------------------------------------------------------
#
