[build-system]
requires = ["setuptools >= 75"]
build-backend = "setuptools.build_meta"

[project]
name = "new-horizon"
version = "0.0.1"
authors = [
  { name="Philipp Kroll", email="pk@eample.com" },
]
description = "A Client Library for Interaction with Pluto."
readme = "README.md"
requires-python = ">=3.8"
classifiers = [
    "Programming Language :: Python :: 3",
    "Operating System :: OS Independent",
]
dependencies = [
    "requests>=2.32.5",
    "typing_extensions>=4.15.0",
]

[project.license]
file = "LICENSE"
license = "MIT"
license-files = ["LICENSE"]

[project.urls]
Homepage = "https://github.com/Philipp-Co/pluto"
Issues = "https://github.com/Philipp-Co/pluto/issues"


[project.scripts]
nh_state = "new_horizon.cli.new_horizon_admin_cli:cli"
nh_connect = "new_horizon.cli.new_horizon_admin_connect_cli:cli"
nh_node = "new_horizon.cli.new_horizon_admin_node_cli:cli"
nh_event = "new_horizon.cli.new_horizon_event_cli:cli"
