[build-system]
requires = ["setuptools >= 75"]
build-backend = "setuptools.build_meta"

[project]
name = "Plyto"
version = "0.0.0"
authors = [
  { name="Philipp Kroll", email="pk@eample.com" },
]
description = "Low Latency Event Driven Programming."
readme = "README.md"
requires-python = ">=3.8"
classifiers = [
    "Programming Language :: Python :: 3",
    "Operating System :: OS Independent",
]

[project.license]
file = "LICENSE"
license = "MIT"
license-files = ["LICENSE"]

[project.urls]
Homepage = "https://github.com/Philipp-Co/pluto"
Issues = "https://github.com/Philipp-Co/pluto/issues"

[project.scripts]
plyto_add_node_pt = "plyto.setup.plyto_add_pt_node:cli"
plyto_connect_nodes = "plyto.setup.plyto_connect_nodes:cli"
