# https://docs.docker.com/build/building/multi-stage/
#
#
# Konfiguration unter:
#   /bin/
#       pluto_*
#       ...
#
#   /pluto/config/
#       core.cfg
#       node_name_0.cfg
#       ...
#
#   /pluto/nodes/node_name_0/
#       .venv/
#
#   /pluto/nodes/node_name_1/
#   ...
#


#
# ---------------------------------------------------------------------------------------------------------------------
#
from ubuntu:20.04 as pluto_builder

RUN echo "Europe/Berlin" > /etc/timezone
RUN apt-get update && apt-get upgrade -y
RUN apt install software-properties-common -y
RUN add-apt-repository ppa:deadsnakes/ppa
RUN apt-get install python3.8-dev -y
RUN apt-get install python3-pip -y
RUN apt install python3.8-venv -y
RUN apt-get install cmake -y
#RUN apt-get install python3-dev -y
RUN apt-get install git -y

#
# Copy C Source Files...
#
COPY ../pluto_config/ /pluto_config/
COPY ../pluto_os_abstraction/ /pluto_os_abstraction/
COPY ../pluto_node/ /pluto_node/
COPY ../pluto_edge/ /pluto_edge/
COPY ../pluto_core/ /pluto_core/
COPY ../CMakeLists.txt /
#
# Download external Dependencies like Testframework and JSON Parser...
#
RUN cd / && mkdir /external/ && cd /external/ && git clone https://github.com/zserge/jsmn.git && git clone https://github.com/ThrowTheSwitch/Unity.git
#
# Build the Executables...
#
RUN mkdir /build/ && cd /build/ && cmake -G "Unix Makefiles" -DCMAKE_BUILD_TYPE=Debug -DPLUTO_TARGET_OS=2 -DPLUTO_OS_INTERFACE=1 ../
RUN cd /build/ && make VERBOSE=1
RUN cd /build/ && make install
#
# Create needed Directorystructure...
#
RUN mkdir /pluto/ && mkdir /pluto/core/ && mkdir /pluto/core/config/ && mkdir /pluto/nodes/
RUN touch /pluto/core/config/core.cfg && echo "{\"nodes\":[]}" > /pluto/core/config/core.cfg
#
# Copy Setup Scripts...
#
COPY ./plyto/ /plyto/
#
# Create Venv...
#
RUN python3 -m venv .venv
RUN . .venv/bin/activate && pip install build typing_extensions
RUN . .venv/bin/activate && cd /plyto/ && python3 -m build --sdist && pip install dist/plyto-0.0.0.tar.gz
#
# ---------------------------------------------------------------------------------------------------------------------
#

# Multistage Build

#
# ---------------------------------------------------------------------------------------------------------------------
#

from ubuntu:20.04 as pluto_runtime

#
# Need Python
#
RUN echo "Europe/Berlin" > /etc/timezone
RUN apt-get update && apt-get upgrade -y
RUN apt install software-properties-common -y
RUN add-apt-repository ppa:deadsnakes/ppa
RUN apt-get install python3.8-dev -y
RUN apt-get install python3-pip -y
RUN apt install python3.8-venv -y

#
# Copy Executables from Builder...
#
COPY --from=pluto_builder /usr/local/bin/pluto_core /usr/local/bin/
COPY --from=pluto_builder /usr/local/bin/pluto_node_* /usr/local/bin/
COPY --from=pluto_builder /pluto/ /pluto/
#
# Copy Venv fomr Builder...
#
COPY --from=pluto_builder /.venv/ /.venv/
ENV VIRTUAL_ENV=/.venv/
ENV PATH="$VIRTUAL_ENV/bin:$PATH"
#
# Copy Pluto Directories from Builder...
#
COPY --from=pluto_builder ./pluto/ /pluto/

#COPY ../plyto/ /plyto/
#RUN cd /plyto/ && python3 -m venv .venv
#RUN cd /plyto/ && . .venv/bin/activate && pip install -r requirements.txt
#RUN cd /plyto/ && . .venv/bin/activate && python -m build --sdist

#
# COPY p0.tar.gz /p0.tar.gz
# COPY p1.tar.gz /p1.tar.gz
#                                           # Config unter /etc/pluto/
#                                           #   /etc/pluto/core.cfg
# RUN plyto_add_py_node name_0 /p0.tar.gz   # Legt venv unter /name_0/ an.
#                                           #   /etc/pluto/name_0.cfg
# RUN plyto_add_py_node name_1 /p1.tar.gz   # Legt venv unter /name_1/ an.
#                                           #   /etc/pluto/name_0.cfg
# RUN plyto_connect name_0 name_1
# 
# Example:
# RUN plyto_add_node_pt name_0              # Create a passthrough Node with Name "name_0"
# RUN plyto_add_node_pt name_1              # Create a passthrough Node with Name "name_1"
# RUN plyto_add_node_pt name_2              # Create a passthrough Node with Name "name_2"
# RUN plyto_connect_nodes name_0 name_1     # Connect Node name_0 with Node name_1: name_0 -> name_1
# RUN plyto_connect_nodes name_0 name_2     # Connect Node name_0 with Node name_2: name_0 -> name_2

#
# ---------------------------------------------------------------------------------------------------------------------
#

#
# Start the Container. Execute pluto_core.
# pluto_core will start to manage pluto_nodes according to the given configuration.
#
CMD ["pluto_core", "-c", "/pluto/core/config/core.cfg"]

#
# ---------------------------------------------------------------------------------------------------------------------
#
