# https://docs.docker.com/build/building/multi-stage/

#
# ---------------------------------------------------------------------------------------------------------------------
#
from ubuntu:20.04 as builder

RUN echo "Europe/Berlin" > /etc/timezone
RUN apt-get update && apt-get upgrade -y
RUN apt install software-properties-common -y
RUN add-apt-repository ppa:deadsnakes/ppa
RUN apt-get install python3.8-dev -y
RUN apt-get install python3-pip -y
RUN apt install python3.8-venv -y
RUN apt-get install cmake -y
#RUN apt-get install python3-dev -y
RUN apt-get install git -y

COPY ../pluto_event/ /pluto_event/
COPY ../pluto_config/ /pluto_config/
COPY ../pluto_os_abstraction/ /pluto_os_abstraction/
COPY ../pluto_node/ /pluto_node/
COPY ../pluto_rw/ /pluto_rw/
COPY ../pluto_info/ /pluto_info/
COPY ../pluto_edge/ /pluto_edge/
COPY ../pluto_core/ /pluto_core/
COPY ../CMakeLists.txt /
RUN cd / && mkdir /external/ && cd /external/ && git clone https://github.com/zserge/jsmn.git && git clone https://github.com/ThrowTheSwitch/Unity.git


RUN mkdir /build/ && cd /build/ && cmake -G "Unix Makefiles" -DPLUTO_TARGET_OS=2 -DPLUTO_OS_INTERFACE=1 ../
RUN cd /build/ && make
RUN cd /build/ && make install

#
# ---------------------------------------------------------------------------------------------------------------------
#

COPY ../plyto/ /plyto/
RUN cd /plyto/ && python3 -m venv .venv
RUN cd /plyto/ && . .venv/bin/activate && pip install -r requirements.txt
RUN cd /plyto/ && . .venv/bin/activate && python -m build --sdist

#
# ---------------------------------------------------------------------------------------------------------------------
#
